theme: minima

title: Ryan Drobny
#author: Ryan
#email: 
#url: 

timezone: Etc/UTC # GitHub uses UTC. This is to force dev environment to match
future: false # GitHub Pages will publish future posts if this isn't set to false

description: >
  Ryan's site.

# Minima variables
twitter_username:  
github_username:   
linkedin_username: 
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#rss: rss

show_excerpts: false

# Used by simple links page
social-links:
  Resume:          
  LinkedIn:        https://linkedin.com/in/ryandrobny
  StackOverflow:   
  HackerRank:      
  GitHub:          
  Microsoft Learn: 
  Twitter:         
  Reddit:          
  Credly:          
  PluralSight:     
  Website:         

# plugin: jekyll-seo-tag
twitter:
  username: 
  card: summary_large_image
social:
  name: Ryan Drobny
  links:
    - https://linkedin.com/in/ryandrobny

# plugin: jekyll-titles-from-headings
titles_from_headings:
  strip_title: true

collections:
  personal: # collection for personal blog posts
    output: true

header_pages:
  - about.md




plugins:
  - jekyll-sitemap

google_analytics:



gravatar_hash: 
code_block_max_height: 500px

home_post_limit: 5

# The github repo that is to be used for looking up comments
comments_repo: 

defaults:
  - scope:
      path: ""
    values:
      image: 
  - scope:
      path: ""
      type: posts
    values:
      tags:
        - Other # Add a default tag to all posts

# Disable highlighting to use highlightJS instead
# highlighter: none # Not supported by GitHub Pages
kramdown:
  syntax_highlighter_opts:
    disable: true
